#include <iostream>
#include "Goblin.cpp"
#include "Spectre.cpp"
#include "Orc.cpp"
#include "Credits.cpp"
using namespace std;
void KnightDelilahRoute(){
    int Ready2;
    int Ready3;
    int Ready4;
    int BagOpen;
    int SaveDelilah;
    int FinalChoice;
    cout<<"Of course you choose your childhood best friend! Who would want riches over their friend?"<<endl;
    cout<<"You inquire about the location of the Goblins base to find out where they're keeping her hostage."<<endl;
    cout<<"You find out that they're located on West Yorkshire Mountain, not far at all."<<endl;
    cout<<"You grab your sword and prepare for a glorious journey."<<endl;
    cout<<"Your armor clanks down ye old roads as you hurriedly rush down them."<<endl;
    cout<<"You don't even bother to look at anyone passing by you."<<endl;
    cout<<"Everyone here is unknown to you."<<endl;
    cout<<"You start to pant from how much you're running."<<endl;
    cout<<"Your sweat glistens through your helmet, you can feel your legs chafing."<<endl;
    cout<<"Your sword drags against the ground leaving a line in the dirt."<<endl;
    cout<<"Finally you make it to your first milestone, a forest."<<endl;
    cout<<"What forest? Who knows, it's just there."<<endl;
    cout<<"You keep on your guard knowing that at any moment an ambush could occur."<<endl;
    cout<<"Suddenly you hear a screech in the distance."<<endl;
    cout<<"You whip your head back and see a Rogue Goblin racing at max speeds towards you."<<endl;
    cout<<"His small but sharp dagger shines, and drool drips down his green face."<<endl;
    cout<<"There's no point in asking, but are you ready?"<<endl;
    cout<<"1. Let's end this."<<endl;
    cout<<"2. Wait can we talk about this."<<endl;
    cin>>Ready2;
    switch (Ready2){
        case 1:
            cout<<"Then best of luck!"<<endl;
            RogueGoblin();
            break;
        case 2:
            cout<<"Nice try goblins can't speak english. Good Luck."<<endl;
            RogueGoblin();
            break;
    }
    cout<<"You end the goblin's pitiful life."<<endl;
    cout<<"It lies dead before you, you notice its little dagger has an engraving on it."<<endl;
    cout<<"It's in Orcish, you can't make out a single letter."<<endl;
    cout<<"But you do recognize a small heart in the corner."<<endl;
    cout<<"The goblin has a bag on its waist. Do you dare open it?"<<endl;
    cout<<"1. Yes"<<endl;
    cout<<"2. No"<<endl;
    cin>>BagOpen;
    switch (BagOpen){
        case 1:
            cout<<"You rip open the bag."<<endl;
            cout<<"Therein lies little trinkets."<<endl;
            cout<<"A crude drawing of 3 goblins, presumably a family."<<endl;
            cout<<"A Large green goblin similar to the one who lies dead before you."<<endl;
            cout<<"A Smaller Pink goblin with a flower in its hair. Perhaps a mother of sorts?"<<endl;
            cout<<"And a small goblin in the middle. Possibly their child."<<endl;
            cout<<"You."<<endl;
            cout<<"You're not sure what to feel."<<endl;
            cout<<"You dig a hole for the green creature and bury him properly."<<endl;
            cout<<"You can't help but feel as if this wasn't the right thing to do. Evil or not."<<endl;
            cout<<"You pick yourself up and continue your journey."<<endl;
            break;
        case 2:
            cout<<"You ignore the bag, it might be a trap."<<endl;
            break;
    }
    cout<<"You solemnly continue your journey until you come across a bridge."<<endl;
    cout<<"You can hear whispers."<<endl;
    cout<<"The bridge begins to morph and sway."<<endl;
    cout<<"You feel as if though any moment you might fall through the planks."<<endl;
    cout<<"You can feel someone breathing down your neck."<<endl;
    cout<<"You whip back and see a ghastly figure behind you."<<endl;
    cout<<"There it is. The phantom spectre you've been warned of."<<endl;
    cout<<"You thought it was merely a tale to scare children from wandering off."<<endl;
    cout<<"It stares into your eyes, and you can see the souls of many."<<endl;
    cout<<"You are its next victim."<<endl;
    cout<<"I shouldn't have to ask, but are you ready?"<<endl;
    cout<<"1. What else can I do?"<<endl;
    cout<<"2. Either that or dying I guess."<<endl;
    cin>>Ready3;
    switch (Ready3){
        case 1:
            cout<<"That's the spirit, good luck."<<endl;
            Spectre();
        case 2:
            cout<<"Hey try and be a little more optimistic will ya?"<<endl;
            Spectre();
    }
    cout<<"The Spectre vanishes into thin air the minute you land the finishing blow."<<endl;
    cout<<"A nuisance that has been hunted for millenia has been ended by you."<<endl;
    cout<<"You feel a sense of justice, this is what being a hero is all about."<<endl;
    cout<<"You can feel yourself getting stronger as you progress."<<endl;
    cout<<"You rush on ahead eager to rescue your childhood friend."<<endl;
    cout<<"Memories rush back of the time you spent with her as children."<<endl;
    cout<<"You try and remember anything, but all that really comes to mind is her beauty."<<endl;
    cout<<"The way she would always smile at you even when you said the silliest of things."<<endl;
    cout<<"You're almost there, almost able to save Delilah."<<endl;
    cout<<"Suddenly the ground begins to tremble."<<endl;
    cout<<"The final trial awaits you."<<endl;
    cout<<"From the ground emerges the mighty orc, with a blade three times the size of your entire body."<<endl;
    cout<<"He lets out a roar that shakes mountains."<<endl;
    cout<<"I feel silly even asking this, but are you ready?"<<endl;
    cout<<"1. For Delilah."<<endl;
    cout<<"2. Of course."<<endl;
    cin>>Ready4;
    Orc();
    cout<<"The Mighty Orc falls with a thud."<<endl;
    cout<<"You barely made it out alive."<<endl;
    cout<<"It's by pure chance that you're left alive, had you gotten unlucky who knows what would've happened."<<endl;
    cout<<"You trudge on forward with deep wounds gushing blood like fountains."<<endl;
    cout<<"You can barely stand by the time you've made it to the summit."<<endl;
    cout<<"There lies Delilah, as fair as ever."<<endl;
    cout<<"Trapped inside a cage, only you can free her."<<endl;
    cout<<"You're not sure if you have the strength to free her."<<endl;
    cout<<"Even if you do, it'll be the last of your strength."<<endl;
    cout<<"The end of your journey is here."<<endl;
    cout<<"It is up to you to save Delilah."<<endl;
    cout<<"She stares at you and screams as if she's seen a ghost."<<endl;
    cout<<"What do you do?"<<endl;
    cout<<"1. Break the Cage."<<endl;
    cout<<"2. Go back for help."<<endl;
    cin>>SaveDelilah;
    switch (SaveDelilah){
        case 1:
            cout<<"You want to break the cage."<<endl;
            cout<<"Your blood paints the ground yet you want to break the cage."<<endl;
            cout<<"Your entrails lead behind you like a bread crumb trail."<<endl;
            cout<<"Even so you still wish to break the cage."<<endl;
            cout<<"You trudge forward."<<endl;
            cout<<"Your first step leaves you in immense pain."<<endl;
            cout<<"The second leaves you nearly blind from pain."<<endl;
            cout<<"The third makes your entire body go numb."<<endl;
            cout<<"Finally you arrive at the foot of the cage."<<endl;
            cout<<"This is it, the final moment of your adventure."<<endl;
            cout<<"You raise your sword to the sky."<<endl;
            cout<<"But before you can bring it down to save your childhood love."<<endl;
            cout<<"You hear a scream."<<endl;
            cout<<"Delilah: 'Theseus no!'"<<endl;
            cout<<"Your vision goes completely black."<<endl;
            cout<<"You are dead."<<endl;
            cout<<"You're unsure of what exactly killed you."<<endl;
            cout<<"But you find yourself in an area between time and space."<<endl;
            cout<<"A limbo of sorts."<<endl;
            cout<<"What are you doing here?"<<endl;
            cout<<"Who knows. But you're here now."<<endl;
            cout<<"From the endless abyss you hear a voice."<<endl;
            cout<<"Do you respond?"<<endl;
            cout<<"1. Yes"<<endl;
            cout<<"2. Yes"<<endl;
            cout<<"3. Yes"<<endl;
            cout<<"4. Yes"<<endl;
            cout<<"5. Yes"<<endl;
            cout<<"Yes."<<endl;
            cin>>Ready4;
            cout<<"You call out to whatever being is calling you."<<endl;
            cout<<"???: Are you ready to face me Theseus."<<endl;
            cout<<"Well, are you?"<<endl;
            cout<<"1. Yes"<<endl;
            cout<<"2. Yes"<<endl;
            cout<<"3. Yes"<<endl;
            cout<<"4. Yes"<<endl;
            cout<<"5. Yes"<<endl;
            cout<<"Yes."<<endl;
            cin>>Ready4;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡼⡄⠳⣣⣃⢠⢣⢦⣯⢾⠀⠀⠀⠀⠘⡗⣦⣫⣹⡽⡝⡝⡝⡽⣹⣅⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡷⡐⢤⡵⡽⢋⣾⣿⣟⢸⠀⠀⠀⠀⠰⣧⡇⣷⣿⣟⣜⢮⢮⣮⡾⢶⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⡷⠜⢎⢻⣶⣼⣿⣹⣾⣾⡇⠀⠀⠀⢠⣿⣷⣿⣿⣿⡷⢑⣧⢜⡵⡳⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣯⡪⣦⡱⡽⣿⣿⣧⣿⣿⡷⠀⠀⠀⣾⣿⣿⣧⣿⣿⣭⢟⣵⡫⢊⣽⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣧⣑⢆⡻⣾⡟⣿⣿⣿⢳⣿⡀⠀⢀⣿⣯⣿⣿⣿⣿⣷⡻⡫⢖⣡⣾⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡬⢯⡓⢷⣿⣾⣮⡺⣿⢷⣿⡟⢣⠀⡟⠻⣿⡫⣷⣿⣿⣿⣪⣵⡶⣛⠽⢦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢘"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠴⢞⡢⢬⡑⢼⣿⡛⢿⣟⢼⠟⠁⠸⣼⠁⠀⣹⣯⣿⣦⡤⣺⣿⠅⣉⣤⡴⠿⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈"<<endl;
            cout<<"⠢⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣟⡒⠤⣍⡀⢽⢷⣬⡟⢼⡿⠃⢀⡼⠀⠣⡀⠙⢻⣯⡿⣵⠤⡾⣿⣊⢥⣶⠮⢭⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣤⣆⠀"<<endl;
            cout<<"⢛⣽⣿⣿⣦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣯⠝⢋⣶⣾⠯⢑⣿⣪⣾⢁⣴⠏⠀⠀⠀⠈⠳⡄⢾⣯⣧⣒⠩⣽⣟⢡⣔⡒⢽⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⢞⡭⡾⣝⠀"<<endl;
            cout<<"⠐⣛⣿⣿⣫⣙⣳⢶⣤⣄⣀⢀⠀⠀⠀⠀⢀⡮⠭⠁⣶⣾⣓⣦⣿⢿⡯⣰⠃⠀⠀⠀⠀⠀⠀⠹⡈⢷⡽⣷⢿⣛⣯⡝⠢⠗⢚⡆⠀⠀⠀⠀⠀⠀⢀⣀⡴⣶⢿⡓⢝⡫⢞⡷⠂"<<endl;
            cout<<"⣀⣀⣚⣻⡾⠿⠾⠿⢿⣿⣿⣿⣛⠂⢤⡀⣸⣒⣀⣀⣀⣗⣚⣹⡟⠻⠁⡇⠀⠀⠀⠀⠀⠀⠀⠀⢹⢠⣿⣿⡭⡴⣾⡗⠒⠉⢉⡆⠀⢀⣠⠦⢲⣲⣿⣟⣻⡿⠛⠚⠁⣾⣽⠯⠭"<<endl;
            cout<<"⠀⠀⠀⡔⠾⣯⡉⢀⣀⡹⣿⣿⣿⠄⠀⠙⣷⠤⠀⢐⣒⣺⡦⢼⣟⢸⡆⢿⠀⠀⠀⠀⠀⠀⠀⠀⣼⠈⡇⢰⡿⠧⣽⢀⣈⡛⢛⡅⢰⠋⠀⢠⣯⡿⢏⣽⣟⣉⡁⠀⣲⣞⣉⣩⣀"<<endl;
            cout<<"⠀⠀⠒⢭⣛⠋⣼⠾⣭⣗⢚⣿⣿⣿⡀⣠⠩⣏⡁⠤⣔⡾⢯⡉⢇⡈⢧⠘⡄⠀⠀⠀⠀⠀⠀⠀⡟⢰⠇⢘⣭⣽⣟⣣⠤⠖⣚⡗⢯⠀⢀⣫⣟⣻⠿⠍⠖⠶⣶⣾⠙⢒⣂⣀⡀"<<endl;
            cout<<"⠁⠀⠊⢉⢠⣟⢦⡛⣽⢷⠭⣚⣿⣿⣶⠸⡇⢻⡂⣭⣶⣴⣾⢿⣿⣿⣶⣣⡈⢦⠀⠀⠀⠀⠀⡼⢡⢎⣰⣿⣷⣾⣯⡍⠛⠳⡞⠀⢸⡆⢹⣿⣾⡿⠯⠉⢀⣾⣛⡯⠷⣲⢤⠶⠄"<<endl;
            cout<<"⠲⣒⣉⡡⢞⡶⢛⡨⠓⣹⣪⡔⣛⣷⣿⡅⢧⠀⠙⢷⠟⣉⠕⣪⢿⣾⣿⣿⣳⢘⣶⠀⠀⠀⢠⡇⢾⣾⣿⣿⣷⣮⣍⡙⢳⡞⠁⢀⡞⠀⣴⣯⣞⡟⠻⠶⣶⣫⡍⣙⡛⠶⠶⣣⣤"<<endl;
            cout<<"⣀⡈⠛⢦⡴⣊⡥⢂⢴⡺⠻⣾⣵⣾⣯⣻⣎⠻⢆⡈⠙⠰⣯⣺⣿⣿⣯⣿⡧⢲⣿⣏⣿⣟⣹⣷⢤⣼⣿⣿⣿⣯⣻⡞⠃⠀⣠⠜⠁⣰⢿⡾⡟⠊⢽⣲⡿⣒⠩⢕⣊⠩⡵⠖⢃"<<endl;
            cout<<"⣝⠚⢹⠿⣿⣶⣴⣿⣻⣶⠺⠿⠿⣴⡻⣦⡉⠙⠣⢤⣤⡤⠤⢭⣙⠻⣿⢻⡿⠊⠀⣀⣀⣀⡀⠙⠪⡿⢿⡟⠛⣋⣉⣉⣉⣡⡤⠔⣫⣰⡿⡽⠯⠙⠒⠛⢫⣷⣬⡵⢾⣾⣿⡛⠉"<<endl;
            cout<<"⢯⠭⠤⠄⢈⣳⣿⡻⣿⣿⣿⣀⠀⠀⣿⣾⢝⡳⢶⢶⣾⣿⣾⣿⣧⣶⠿⡿⠀⢠⣾⠿⠟⠻⢿⣶⡀⠱⣿⣷⣿⣷⣿⣯⣿⣤⣤⣾⣿⣯⡟⠀⢠⣶⣦⡾⢿⣏⢩⣬⢏⣁⠀⠀⢀"<<endl;
            cout<<"⠈⠁⣖⡽⠟⣹⠟⣻⣾⣟⡿⣿⣀⡀⣹⡾⡻⢻⢳⣻⡿⣿⣿⣿⡿⢷⣶⡇⣠⡟⠁⣾⢿⣿⠀⠈⣧⡀⣷⣾⣿⣿⣿⣿⢻⠿⠟⡞⣗⣹⡇⢀⣶⣿⣛⣿⣷⢘⡛⠯⢇⣶⣶⣖⠨"<<endl;
            cout<<"⠅⡠⠷⣳⢯⣴⣎⣵⣟⡹⣿⣟⣿⣷⡘⠹⣧⣆⣦⣫⠷⢚⣩⣥⣤⢸⣭⣷⠉⠙⢦⡘⠒⢚⣠⡖⠉⢡⣿⣏⣨⣍⡛⢿⣼⣰⣰⣰⠿⠙⣥⣿⣿⣛⣲⣿⢯⣑⣾⢟⣶⣟⡻⣖⠭"<<endl;
            cout<<"⠀⠠⢊⡴⡫⡫⣪⢛⢿⣞⢼⣿⡿⣿⡶⣦⣀⣀⣀⡤⣾⣿⣿⣿⣿⣼⣿⣽⣆⠀⠀⠙⠛⠛⠉⠀⣠⣮⣻⣿⣼⣿⣿⣷⣤⣄⣀⢤⢴⣟⣿⣿⣾⣿⡾⣻⣷⡿⣮⡺⣷⣽⡫⣕⢬"<<endl;
            cout<<"⣂⡴⢋⢜⠜⡱⡱⣵⣿⢻⣧⣟⢴⢿⢟⠷⡯⡤⣾⣿⣿⣿⣿⣿⣿⡟⠉⣻⢯⣿⣶⢤⣤⡤⢴⣮⣽⣟⠁⠙⣯⣿⣿⣿⢯⡽⡤⣴⢿⣿⣯⢻⢎⢮⣷⣟⢽⣿⣿⣿⣮⡫⡙⠢⡑"<<endl;
            cout<<"⠀⠁⠙⠿⣞⣠⡟⡨⡣⣡⣉⢛⢶⣡⣿⡽⣼⣼⡤⡟⣏⢿⣉⢻⡟⢰⣯⣿⣶⣿⣿⣾⣿⣿⣾⣿⣧⣿⣷⡄⢹⣏⣏⢿⣿⣧⣿⣿⣰⣸⢿⣧⢿⢿⡝⣮⢶⡿⡿⢷⣄⠱⣎⣳⡬"<<endl;
            cout<<"⠀⠀⠀⠀⠈⠻⢾⣕⣵⣱⢃⡎⡞⣾⡾⠓⠻⢼⣷⣇⣟⣌⣿⠟⣱⠛⣻⣿⣿⣿⢿⣟⠼⠹⢿⣿⣿⣿⣿⣿⢆⠙⠿⢾⣽⣸⣸⣾⡿⠯⠿⢿⣿⣷⢿⡜⣷⡳⡘⢶⣌⡇⠁⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠉⠙⠻⠞⠚⢲⡟⠀⠘⢷⡄⠈⣡⣀⣁⣤⣾⣷⢶⢿⡟⠘⣿⣧⣷⠀⠀⢸⣿⡿⣿⡿⢿⣦⣙⢢⣄⡁⢸⣏⣥⡤⠟⠀⠀⣻⠦⡷⣸⠾⠛⠛⠚⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⢀⣼⣿⣿⣿⣿⣯⣿⣟⣯⢻⢾⣾⣌⢮⢌⠺⡇⠀⠀⠐⡟⣸⢫⢟⣷⡿⣻⣿⣿⣿⣿⣿⣿⣧⢀⠀⠀⡼⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢳⣽⣿⣟⣾⣷⡿⣿⣿⣿⣏⣿⡿⡟⢌⢦⠳⣵⡟⠀⠀⠐⣖⡵⡱⢃⠟⡻⣯⣼⡽⡿⣫⢞⣿⢻⣽⣶⡼⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣻⣿⣯⠸⣿⣿⣿⣿⣿⣿⣮⡮⣢⣕⢬⠁⠀⠀⠀⢸⡞⣔⣵⣾⣿⣿⢗⣸⣷⡡⣺⢿⣿⢿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣯⣿⣟⠻⡓⣿⣿⣟⠻⣿⣿⣿⣿⣾⠛⠉⠀⠀⠀⠀⠀⠙⣿⣿⢓⡡⣒⣭⣿⣟⡜⡽⣿⣷⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⣧⡺⣮⣿⣿⣷⢟⢟⢽⡻⣽⡳⣄⠀⠀⠀⠀⣠⡾⡫⢓⠥⢚⡡⢊⣽⣯⢜⣼⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣧⡙⢼⡷⢝⢿⣷⡑⢝⡪⣻⣟⢿⣷⣄⣴⡿⠕⡩⠞⣁⠔⢁⢴⢿⢿⡧⢚⣿⡿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣷⢄⢕⢄⡑⠦⡉⠪⣒⠑⠭⡿⣿⡷⠋⡠⢖⡡⠒⢁⣕⢵⢟⣳⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢻⣿⣿⡙⢏⡙⠢⣌⠐⣄⡙⢦⡈⠻⣿⣦⡴⠯⡠⠖⣁⠕⣡⣾⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣷⣕⣆⣩⡢⣄⠑⢭⡈⠢⣿⣲⣌⠻⣯⣊⡤⢚⣵⣾⣾⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢫⡻⣿⡪⣗⢵⢌⡲⣶⣔⣟⠟⣷⣜⢻⣖⣵⣿⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣯⡛⢷⣽⣧⡈⠪⡳⣷⣳⢜⢿⣷⣙⣟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣷⣬⣹⣿⣶⣈⠺⣮⡳⣕⣿⣝⢯⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣮⢞⣽⠿⣿⣿⢿⣿⡿⠿⠻⣷⣌⢾⣮⡻⡌⢢⠱⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⢯⡾⢃⡜⢹⣵⠟⠋⠀⠀⠀⠉⠻⣷⣽⣿⣾⣦⠱⣵⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠞⣰⡫⠞⠙⠁⠀⠀⠀⠀⠀⠀⠀⠀⠙⠛⢿⣧⡳⣽⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠊⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠓⢾⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"???: Greetings Theseus. Do not speak, you are no longer capable."<<endl;
            cout<<"Whatever that thing is, is right. Your entire mouth is gone."<<endl;
            cout<<"???: I find your intentions noble. So I will pity you."<<endl;
            cout<<"What? Pity? For what?"<<endl;
            cout<<"???: You are in no position to question me. Silence your thoughts."<<endl;
            cout<<"..."<<endl;
            cout<<"???: Much better."<<endl;
            cout<<"???: You Theseus have pleased me, your actions are beyond noble."<<endl;
            cout<<"???: Therefore I shall grant you an ultimatum."<<endl;
            cout<<"???: Your short lived journey will be substantiated."<<endl;
            cout<<"???: You may choose to rid the underworld of its endless scum. And be remembered as a hero."<<endl;
            cout<<"???: Or you may choose to live again, a new life. A life that isn't guaranteed."<<endl;
            cout<<"???: However. These things are not free."<<endl;
            cout<<"???: Make your choice, and I shall reveal all."<<endl;
            cout<<"1. Rid the underworld of its scum."<<endl;
            cout<<"2. A new life."<<endl;
            cin>>FinalChoice;
            switch (FinalChoice){
                case 1:
                    cout<<"???: You choose to rid the underworld of its scum? A worthy cause."<<endl;
                    cout<<"???: However, I can only grant you this on a condition."<<endl;
                    cout<<"???: A condition you have already agreed to."<<endl;
                    cout<<"???: After you have rid the underworld of its evil, you will sign a contract with Helios to end all slaughter of demons."<<endl;
                    cout<<"???: In exchange, you will become a demon as well. Rid of all of your humanity."<<endl;
                    cout<<"???: You will spend an eternity guarding your section of hell."<<endl;
                    cout<<"???: When the time is right, I will contact you once again."<<endl;
                    cout<<"???: From there, you will be tested once more. To see if you please me again."<<endl;
                    cout<<"???: Theseus. Go forth and become a hero, or die trying to become one."<<endl;
                    cout<<"???: I can see you are still worried."<<endl;
                    cout<<"???: Do you fear for the girl?"<<endl;
                    cout<<"???: I am sorry to tell you this, but the girl is dead."<<endl;
                    cout<<"???: What you see there is an illusion created by orcish wizards."<<endl;
                    cout<<"???: You had been tricked. As noble as your intentions seemed."<<endl;
                    cout<<"???: I am sorry Theseus. Delilah now roams the depths of Hades."<<endl;
                    cout<<"???: Perhaps you shall meet again."<<endl;
                    cout<<"???: For now. Begone with you, finish your adventure."<<endl;
                    cout<<"???: Your actions matter Theseus."<<endl;
                    cin>>FinalChoice;
                    cout<<"Ending 5/12 A Hero's Beginning"<<endl;
                    cout<<"[xxxx-7xxx-xxxx]"<<endl;
                    Credits();
                    break;
                case 2:
                    cout<<"???: A new life."<<endl;
                    cout<<"???: Very well then, your new life will be one of an angel."<<endl;
                    cout<<"???: However, you are fated to die the most gruesome death."<<endl;
                    cout<<"???: Your new name. Azrael."<<endl;
                    cout<<"???: You will meet your demise to someone all too familiar."<<endl;
                    cout<<"???: Helios will not grant you mercy however."<<endl;
                    cout<<"???: You will be a warrior of endless riches and glory."<<endl;
                    cout<<"???: But when the time comes you will be ended by hands you know all too well."<<endl;
                    cout<<"???: We are not the only versions of us Theseus."<<endl;
                    cout<<"???: This world is not as simple as it may seem."<<endl;
                    cout<<"???: Even as we speak an infinite amount of Theseus' have made the same or opposite choice as you have."<<endl;
                    cout<<"???: You will meet yourself again. And we will have this conversation again."<<endl;
                    cout<<"???: An infinite amount of times."<<endl;
                    cout<<"???: And you. You know yourself. Is it worth it?"<<endl;
                    cout<<"???: Is it worth what you're doing?"<<endl;
                    cout<<"???: You infuriate me. Begone now, claim what you came for and leave."<<endl;
                    cout<<"Ending 6/12 A New Infinite Life."<<endl;
                    cout<<"[xxxx-x2xxx-xxxx]"<<endl;
                    cin>>FinalChoice;
                    Credits();
            }
            break;
        case 2:
            cout<<"You decide to go back for help."<<endl;
            cout<<"You turn your head and feel a pain in your abdomen."<<endl;
            cout<<"The orc wasn't dead."<<endl;
            cout<<"Your upper half falls to the ground leaving only your legs standing."<<endl;
            cout<<"Your intentions were noble, but perhaps you shouldn't leave things unfinished huh?"<<endl;
            cout<<"⣭⣀⣺⢻⡿⠛⣯⣿⣿⣿⣽⡟⠛⠿⣿⣾⣿⣟⡛⠛⠒⠩⠈⠘⠐⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠂⡀⠀⣧⣴⡠⠊⢀⣼⣀⣔"<<endl;
            cout<<"⣿⠉⠉⠛⢦⣼⣿⣿⣷⡶⠶⢯⣍⠀⠐⠤⢀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⣤⣤⣠⣤⣤⣶⣿⣿⣿⣿⣧⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠖⣃⠈⠙⢚⣰⠛"<<endl;
            cout<<"⣿⡄⠘⠘⣢⡾⣿⡿⣿⣆⣠⠺⣿⠀⠛⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠤⠖⠛⢑⣫⣝"<<endl;
            cout<<"⣿⣧⢶⠺⡭⢽⣼⣷⣿⣿⡧⢶⣟⠐⠒⠐⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⢤⠩⢽⣓"<<endl;
            cout<<"⡿⣿⣿⢂⣢⡾⣿⣿⡿⡿⡶⢞⣿⣮⡁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠄"<<endl;
            cout<<"⣶⣾⣿⡿⢿⣷⠾⣿⣟⡂⠠⢈⠈⠁⠠⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⢅"<<endl;
            cout<<"⠛⠛⣾⣳⣾⣁⠈⠉⣄⣀⠙⠒⠾⠦⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⠤⡸⢿⣷⣚⣻⣛⣷⣤⣤⡭⠀⢀⣁⡀⠀⠈⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"<<endl;
            cout<<"⡶⡟⢺⡁⣛⣇⣬⡝⢍⣁⢠⣬⡁⡉⣑⡂⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣚"<<endl;
            cout<<"⣴⡶⠚⠉⠁⢀⡆⠹⣬⣖⣀⡴⠈⠀⠀⠀⠒⣶⣄⣀⡀⡀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⢉⣷"<<endl;
            cout<<"⠃⡛⠢⠤⣞⡾⣦⣜⡛⢃⢤⡉⠢⢔⢋⡷⣤⣤⡤⣤⡀⠈⠁⣾⣿⣿⣿⣯⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⢀⣀⡀⠐⠀⣀⠴⡀⠀⣠"<<endl;
            cout<<"⠂⠠⠀⠀⣥⣠⠄⠢⠉⠁⠀⠐⠂⠉⠉⠙⠋⣹⣿⣵⣾⡓⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⡂⣰⣿⣿⣿⣿⣷⣶⣫⣁⡵⠜⢛"<<endl;
            cout<<"⠀⠀⠀⠀⠀⠉⠀⠃⠉⠉⣁⡁⠈⠙⢻⠿⣌⣉⣉⡁⢒⣶⣿⣿⣿⣿⣿⣿⠿⠋⠿⢹⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⡝⣿⣿⣿⣿⣿⣷⣿⣿⡿⣿⣌⢹⣿⣷⣶⢄⣀⡴"<<endl;
            cout<<"⠀⠈⠙⠒⠒⠒⠒⠛⠛⢭⣭⣀⠀⠈⠁⠈⠉⠀⠤⠟⠟⣿⣿⣿⣿⣿⣿⣿⠃⠐⠂⢸⣿⢹⣿⠟⠹⡟⢻⣿⣿⡆⠀⠸⣿⡟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡎⠛⢻"<<endl;
            cout<<"⠀⠁⠀⠀⢰⡿⡟⠶⣖⠶⢒⣚⣟⣿⠿⠷⠷⠴⠤⣶⣶⣿⣿⠟⠙⣻⣿⣿⠀⠠⠀⣾⣟⣾⣏⠀⠀⣇⢹⣿⣿⡇⠀⠀⢸⡧⠀⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⠃⠀⠐"<<endl;
            cout<<"⣄⣤⠖⠒⠛⢷⣿⡗⠛⠛⠉⠁⠀⣀⣶⡂⡀⣤⣾⣻⣿⣿⣿⠀⢠⣿⣿⠇⠀⠀⠀⣿⣿⣍⣘⡀⠸⡿⢡⡿⣿⢳⠀⠀⠈⣷⠀⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠘⢶"<<endl;
            cout<<"⡶⡿⡶⣔⣦⣈⢿⢲⣦⡈⣁⣤⣾⣿⡏⣧⡟⣽⣿⣿⣿⣯⣿⠂⠸⠻⠃⠀⠀⠀⣼⣿⣿⠘⠛⠛⠀⣷⠀⠀⠙⠻⢶⣄⠀⢿⡀⠀⣻⣿⣿⣿⣿⣿⣿⣿⣿⣟⣻⣄⣾"<<endl;
            cout<<"⠉⠙⠿⣧⢧⣤⣾⣶⠷⣿⣷⣿⣶⣿⡗⣿⣿⣿⣿⣿⣿⠈⠁⠀⠀⠀⠀⠀⠀⢰⣿⡿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠰⠛⠉⠀⣾⡟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿"<<endl;
            cout<<"⠶⠒⠀⠀⠂⢀⣽⡿⠶⠛⠋⠋⣹⡆⡇⠛⣿⣿⣿⣿⡏⠀⠀⠀⠀⡀⠀⠀⠀⢸⣿⣇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⡀⢹⣇⠉⠑⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿"<<endl;
            cout<<"⢀⣂⣤⠶⠚⠋⠁⠄⠖⠀⠐⢲⡏⡀⡇⡈⢻⣏⣿⣿⠇⠀⠀⠀⢠⡇⠀⠀⠀⢸⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⡍⠘⣿⠀⠁⢨⣿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿"<<endl;
            cout<<"⠏⣁⠀⢴⡂⣐⣲⡴⢂⡈⠙⣞⡷⣿⣇⠓⠸⣿⢻⣿⣀⣀⣀⠀⢸⡄⠀⠁⠀⢸⣿⣿⡇⠀⠁⠀⠀⠀⡄⠀⠀⠀⠀⠈⠳⠀⣿⠲⡇⢸⣿⣿⣣⣶⡖⡛⠛⠛⠛⠛⠻"<<endl;
            cout<<"⣦⣼⣇⠈⠃⠀⠛⣇⢀⣠⣤⣿⣴⣿⣬⠷⣶⣿⣶⣿⣿⣟⡋⡤⢿⠃⠀⠀⠀⢸⣿⣿⠀⠀⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠛⠛⢤⣿⣿⣿⣿⣿⣿⣯⣟⡷⠰⡷⡀⠀"<<endl;
            cout<<"⡷⠈⠈⠉⠹⠿⣿⠟⢿⣷⣭⡅⠨⣏⠙⠶⣼⣿⡧⣿⠁⡙⠏⣲⣸⡄⠀⠀⠀⢸⣿⣿⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣏⠑⠒⠶⠚⠂"<<endl;
            cout<<"⣉⣽⣵⣤⣾⣿⣾⣿⡿⠟⠋⢙⡻⣶⣶⣶⣿⣇⠀⠄⣠⣤⡤⠽⠿⠃⠀⠀⠀⢺⣿⣹⠀⠀⠀⠁⠀⣄⠀⠀⠀⠀⠀⠀⠀⠙⠟⢛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣤⣤⣴"<<endl;
            cout<<"⠏⠉⠷⣾⣿⣿⣿⣿⣷⣦⡀⠈⢡⡈⡿⣿⣿⣿⡀⠀⣿⠁⠀⠀⠀⠀⠀⠀⠀⣼⣿⣟⡇⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⢰⠟⠋⠙⣿⡏⣩⣿⡿⣿⣿⣟⡉⠀⠉"<<endl;
            cout<<"⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⣽⢾⣿⣿⣇⠙⢸⣿⡆⠀⢀⠀⠀⠀⣠⣾⣿⣿⣿⡇⠀⠀⠀⠀⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⢿⣿⣾⣿⣸⣸⣃⣀⠀⠀⠀"<<endl;
            cout<<"⡗⠂⠄⢀⢀⣀⣛⣛⣻⣿⣿⣿⣿⣧⣀⠈⠻⢿⣿⡏⣹⣷⠸⠘⣇⣀⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⢀⣿⡟⠀⠀⠀⠀⠀⠀⢠⣤⡄⢠⣿⣿⣿⣟⣛⣛⣛⢛⣯⣏⣀⣀"<<endl;
            cout<<"⣧⣄⡀⠈⠨⠄⣭⣭⣍⠉⠻⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣤⣽⢿⣿⣿⣾⣿⣿⣿⣿⣷⡄⠀⠈⢿⣗⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⣿⣿⡏⠉⠩⠥⣤⣤⠀⠀⠙"<<endl;
            cout<<"⠿⢿⣟⣛⠶⣄⡀⠁⠷⣶⣶⣶⣿⣿⡿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣃⣽⣏⠳⣄⠀⠘⢿⣿⡿⠇⠀⠀⠀⠀⠀⢀⣾⣿⠧⠐⡤⢒⣠⠀⠶⠤⢭⣉⣀"<<endl;
            cout<<"⡆⠺⠈⠙⠳⣮⣿⣦⡻⢿⣉⠛⣻⡿⢛⣢⣶⢰⣀⣿⣟⡻⡿⡧⢠⣿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣷⣔⡈⠟⢻⣆⡀⠀⢀⣠⣾⣿⠋⠀⠀⠀⠋⠕⠰⢲⠢⢀⢄⠀⢀"<<endl;
            cout<<"⡅⢠⣦⣤⣾⣿⣿⡿⢻⣞⠻⣿⣿⣿⣶⣾⣭⣸⣿⣿⣿⣷⣷⣿⣏⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣥⣤⣠⠴⠤⠤⡤⣐⣀⡀⣉⠀⠀⠂"<<endl;
            cout<<"⡿⣿⣟⣿⣿⣿⣿⣿⣿⣿⣖⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣠⣲⣿⣿⣶⣗⣤⡤⠄⠀⠀⠀⢸⠀⠀"<<endl;
            cout<<"⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠹⣽⣿⣿⣿⣿⣿⣿⣿⣥⣀⣀⣀⣁⠂⠑⠲"<<endl;
            cout<<"⣧⢬⣻⣿⣿⡈⣿⣿⣿⣿⣿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣁⣯⣽⣿⣿⣿⣿⣶⣿⣿⠟⠉⠉⠉⣦⠀⠀⠄"<<endl;
            cout<<"⣏⠁⠘⣿⣿⣧⣈⢻⣿⡿⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣏⠀⠀⠀⠀⢸⠈⠐⠚"<<endl;
            cout<<"██╗░░░██╗░█████╗░██╗░░░██╗  ██████╗░██╗███████╗██████╗░ ██████╗░░█████╗░██████╗░  ███████╗███╗░░██╗██████╗░"<<endl;
            cout<<"╚██╗░██╔╝██╔══██╗██║░░░██║  ██╔══██╗██║██╔════╝██╔══██╗ ██╔══██╗██╔══██╗██╔══██╗  ██╔════╝████╗░██║██╔══██╗"<<endl;
            cout<<"░╚████╔╝░██║░░██║██║░░░██║  ██║░░██║██║█████╗░░██║░░██║ ██████╦╝███████║██║░░██║  █████╗░░██╔██╗██║██║░░██║"<<endl;
            cout<<"░░╚██╔╝░░██║░░██║██║░░░██║  ██║░░██║██║██╔══╝░░██║░░██║ ██╔══██╗██╔══██║██║░░██║  ██╔══╝░░██║╚████║██║░░██║"<<endl;
            cout<<"░░░██║░░░╚█████╔╝╚██████╔╝  ██████╔╝██║███████╗██████╔╝ ██████╦╝██║░░██║██████╔╝  ███████╗██║░╚███║██████╔╝"<<endl;
            cout<<"░░░╚═╝░░░░╚════╝░░╚═════╝░  ╚═════╝░╚═╝╚══════╝╚═════╝░ ╚═════╝░╚═╝░░╚═╝╚═════╝░  ╚══════╝╚═╝░░╚══╝╚═════╝░ "<<endl;
            exit(0);
            break;
    }
}