#include <iostream>
#include "Hero.cpp"
#include "RoyalGuard.cpp"
#include "Paladin.cpp"
using namespace std;
void KnightRichesRoute(){
    int UselessChoice3;
    int Riches;
    cout<<"Riches? Really?"<<endl;
    cout<<"You decide to abandon Delilah, for something far more materialistic."<<endl;
    cout<<"An odd choice. But it is what you wanted."<<endl;
    cout<<"You gather information about this supposed corrupt king."<<endl;
    cout<<"You learn his fortress lies in the center of the city."<<endl;
    cout<<"You grab your sword and swing it over your shoulder, ready for a long adventure."<<endl;
    cout<<"You run towards the center of the city."<<endl;
    cout<<"Why did you even pick riches?"<<endl;
    cout<<"Are you ok? Do you even need money?"<<endl;
    cout<<"Wasn't the whole point of this to be a hero?"<<endl;
    cout<<"Why bother with money?"<<endl;
    cout<<"Before you can kill yourself with words you finally arrive at your first trial."<<endl;
    cout<<"A Lone Hero stands before the entrance."<<endl;
    cout<<"Doesn't look like he's one for words."<<endl;
    cout<<"Hero:'Hey man you're not supposed to be here.'"<<endl;
    cout<<"? Spoke too soon I guess?"<<endl;
    cout<<"Hero:'Hi I'm the guard Salazar and like I don't wanna have to hurt you man so if you'd just get on your way. That'd be awesome'"<<endl;
    cout<<"What is this guy on about..."<<endl;
    cout<<"I guess the only way to get your riches is to get through this guy?"<<endl;
    cout<<"You raise your sword to face him."<<endl;
    cout<<"Salazar: 'Bro. What's the point.'"<<endl;
    cout<<"This guy sure does love talking doesn't he..."<<endl;
    cout<<"Salazar: Fine I'll fight you, for the king and all that."<<endl;
    cout<<"Are you sure you wanna beat this guy up?"<<endl;
    cout<<"1. I guess?"<<endl;
    cout<<"2. How else am I gonna get my money?"<<endl;
    cin>>UselessChoice3;
    cout<<"Good point, Good luck."<<endl;
    Hero();
    cout<<"Well that guy's dead now."<<endl;
    cout<<"Again, was this really worth it?"<<endl;
    cout<<"Like I'm genuinely confused as to why you'd pick riches???"<<endl;
    cout<<"Once again before you're able to verbally slander yourself you're faced with another foe."<<endl;
    cout<<"Before you stands the Royal Guard."<<endl;
    cout<<"Royal Guard: 'Halt in the name of the King!'"<<endl;
    cout<<"Yikes this guy sounds like a yapper."<<endl;
    cout<<"Let's deal with him quick yeah?"<<endl;
    cout<<"1. Fine"<<endl;
    cout<<"2. Let's end his yappin."<<endl;
    cin>>UselessChoice3;
    cout<<"Royal Guard: For the king!"<<endl;
    RoyalGuard();
    cout<<"Well that's another guy dead..."<<endl;
    cout<<"How do you plan to face the people after this?"<<endl;
    cout<<"You'll be regarded as scum for abandoning Delilah you know that right?"<<endl;
    cout<<"Like why would you even?? Did she break up with you or something??"<<endl;
    cout<<"Once more before you're able to question yourself further your final trial appears."<<endl;
    cout<<"Dark Paladin: Insolent fool."<<endl;
    cout<<"Uh oh, this guy means business."<<endl;
    cout<<"Dark Paladin: You tread upon holy grounds and dare to stain it with blood?"<<endl;
    cout<<"Hey bro I know this isn't the time but this guy will 100% kick your @##"<<endl;
    cout<<"Dark Paladin: Face me coward. Your bloodshed ends here."<<endl;
    cout<<"Uh oh, You're on your own buddy."<<endl;
    cout<<"Dark Paladin: I shall strike you down where you stand."<<endl;
    cout<<"... uhmm are you ready?"<<endl;
    cout<<"1. I think I'm going to die"<<endl;
    cout<<"2. Easy clap."<<endl;
    cin>>UselessChoice3;
    Paladin();
    cout<<"Against all odds you manage to defeat the Dark Paladin."<<endl;
    cout<<"Ok be honest how many tries did that take, 2? 3?"<<endl;
    cout<<"You near the King's throne room. Where all your riches await."<<endl;
    cout<<"This is all pretty pointless, because the riches will be taken by the government anyways."<<endl;
    cout<<"Honestly I think you're pretty retarded for picking this route but you do you I guess."<<endl;
    cout<<"What? I talk too much?"<<endl;
    cout<<"Well too bad, I'm the narrator. You have to listen to me regardless."<<endl;
    cout<<"Oh you made it. Well I guess this is your final choice."<<endl;
    cout<<"Wait a minute."<<endl;
    cout<<"You don't actually want these riches do you?"<<endl;
    cout<<"Ahh I seeeee."<<endl;
    cout<<"You just wanted to see what would happen right?"<<endl;
    cout<<"This doesn't mean a thing to you."<<endl;
    cout<<"It could matter less whether it was riches or Delilah."<<endl;
    cout<<"It's never mattered to you. Theseus is in tears."<<endl;
    cout<<"You killed people he's admired for years. With his hands."<<endl;
    cout<<"Is it really worth it?"<<endl;
    cout<<"Do you understand what you're doing?"<<endl;
    cout<<"???: Cease."<<endl;
    cin>>UselessChoice3;
    cout<<"You find yourself at the door."<<endl;
    cout<<"Your final decision all that stands between you and your riches."<<endl;
    cout<<"You enter through the door and see the King at his throne."<<endl;
    cout<<"King: You have finally arrived."<<endl;
    cout<<"He seems apprehensive."<<endl;
    cout<<"King: I will cooperate as you have slaughtered my strongest solider."<<endl;
    cout<<"King: Just answer me one question."<<endl;
    cout<<"King: Why do you seek my riches?"<<endl;
    cout<<"Well. Answer him."<<endl;
    cout<<"1. I want to be rich."<<endl;
    cout<<"2. I don't know..."<<endl;
    cin>>Riches;
    switch (Riches){
        case 1:
                cout<<"King: Such a reason is unbefitting of a true king."<<endl;
                cout<<"King: I will not stand for it."<<endl;
                cout<<"The king removes his robe to reveal armor of pure gold, gleaming in the summer light."<<endl;
                cout<<"You lift your sword, but before you're even able to get it off the ground everything goes dark."<<endl;
                cout<<"You haven't died. Not yet."<<endl;
                cout<<"You wake up dazed, facing a crowd."<<endl;
                cout<<"Where are you?"<<endl;
                cout<<"Well isn't it obvious? You're being executed."<<endl;
                cout<<"You did ask for this after all."<<endl;
                cout<<"Reap what you have sown."<<endl;
                cout<<"The executioner pulls the lever and the guillotine falls."<<endl;
                cout<<"In but a second your head rolls into a bucket."<<endl;
                cout<<"Your adventure ends in a whimper."<<endl;
                cout<<"You will not be remembered."<<endl;
                cout<<"Ending 7/12, A Useless Hero"<<endl;
                cout<<"[xxxx-xx7x-xxxx]"<<endl;
                Credits();
                break;
        case 2:
                cout<<"King: ..."<<endl;
                cout<<"King: Begone."<<endl;
                cout<<"The King is disgusted by you. Your senseless actions apall him."<<endl;
                cout<<"You turn around to leave and begin to walk out hopelessly."<<endl;
                cout<<"You aren't even granted the honor of death."<<endl;
                cout<<"You are left to live out the rest of your days as a murderer ostracized from civilization."<<endl;
                cout<<"You have no riches, and you have no Delilah."<<endl;
                cout<<"This IS what you asked for. Isn't it?"<<endl;
                cout<<"⢰⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⡖"<<endl;
                cout<<"⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏"<<endl;
                cout<<"⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⢿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠟⠛⠉⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠛⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⢄⡄⠀⠀⠙⣽⣿⠛⠿⣿⢟⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣿⣿⣿⣿⣿⣿⣿⠿⠛⠉⠁⠀⠀⠀⠀⢀⣀⣀⣀⣠⣀⣀⢀⠀⠀⠀⠀⢀⠄⡒⠀⠀⠀⠀⠀⠀⠈⠑⢶⣤⣿⡏⠀⡟⠁⠀⠀⠀⠉⠛⠻⠿⢿⣿⣿⣿⡿⠟⠛⠛⠉⠉⠉⠉⠙⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣿⣿⣿⠿⠛⠉⠀⠀⠀⡠⠀⣀⠀⡠⣴⣿⣿⣿⣽⣯⣿⣿⣿⣿⣶⡤⣺⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠩⡻⡷⡤⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡺⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⠿⠋⠁⠀⠀⠀⠀⡠⢢⡤⣧⢹⢏⣼⣿⣿⣿⣿⣿⢿⡿⣟⠯⢛⣿⣣⠅⠀⠐⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⡛⡄⠀⠀⠀⠀⠀⠀⣠⡰⠓⠈⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⠀⢀⠄⠂⠁⢀⠠⠊⡢⠘⠷⣽⢫⣫⣿⣿⣿⣏⠁⣿⢺⣱⣿⣴⡿⢋⢧⣄⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢖⠘⠄⠀⠀⠀⠀⠀⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⠀⠁⠀⣀⠔⡁⠀⢣⠸⣹⢞⣕⠳⣝⣿⣿⡿⣿⣿⣿⡔⢻⣿⠋⠠⢸⣿⣟⡰⠀⣠⣤⡃⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠂⢠⠀⠀⠀⠤⠤⠤⠔⢀⠀⠀⠀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠤⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢰⣤⠗⠡⣀⠸⣹⣤⢟⣡⢌⠙⡛⣿⣿⣿⣿⣼⣛⠻⣿⣿⡇⢠⠁⣜⠻⣦⣉⡰⢿⣟⣇⠀⠀⠀⠀⠀⠀⠠⣠⣼⡷⠁⣠⣸⡉⢀⡀⢀⢑⠀⠘⢊⠞⠉⠉⡛⢌⡀⢉⠀⠀⠀⠀⠀⠀⢠⣐⣴⣿⡧⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⠃⠳⡄⢿⣷⠗⣁⣦⣝⣻⡿⠋⣝⡺⣿⣿⣿⣿⣿⣿⡿⣘⠁⣠⡿⣃⠄⠀⠉⢛⡶⢎⡑⢠⣄⠠⣠⠄⢀⣺⣿⣧⣠⣿⣾⣿⣷⣾⣧⣞⣤⣭⣇⢀⡸⠕⣭⢎⣿⣷⣿⣿⣯⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⠸⢿⣳⣿⠞⣕⣺⢧⣯⡿⠋⠖⣶⣬⣉⡱⠛⢿⣿⣿⣿⣏⠔⠀⢼⣿⣂⠉⠒⠥⣞⠀⠀⠈⠛⢾⣿⣷⡿⠿⢛⣩⣿⢿⣿⣿⣿⣿⣿⣿⣿⣼⣿⡾⣽⡻⣿⣏⣿⣿⣿⣿⣿⣿⢿⢟⣫⣙⣥⣿⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢠⡠⠕⠃⢙⡒⠍⠑⠊⠒⠛⠛⠋⠓⠉⡤⠶⢮⣝⡿⣿⡇⢰⣏⣿⣿⡅⠒⠠⠔⡂⠁⠂⠄⠠⡀⠙⢵⠻⡴⣿⡿⣻⣿⣿⣿⡿⣿⣿⣿⣿⣿⣿⣿⡱⣿⣻⢟⡣⢇⡑⢲⠀⣤⣙⣦⣷⣿⣿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⠀⠀⠂⠉⠑⠈⢀⣉⠍⠫⣥⣬⣶⣤⣞⣶⠿⠿⠷⢟⣻⣏⠜⣿⣻⣿⣧⣅⣀⣀⡀⠀⠐⠀⠈⠔⣵⡜⣳⡿⣯⠔⣿⣿⣿⣿⣿⣿⣿⣟⣿⣿⣿⣶⣄⡼⣧⣀⣀⣤⣤⣤⣶⠶⠿⢶⣿⣿⣿⣵⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢠⣠⣈⠲⠒⠀⢁⡀⣀⣤⣤⡤⠄⠊⠉⣀⣀⣄⣤⣶⣿⣿⣼⡿⣿⢹⣟⠀⠇⠀⠀⠈⠁⠀⠀⢑⢮⣿⣿⣻⣼⣾⣿⣿⣿⣿⣿⣿⣿⢿⣿⣽⣿⣿⣿⣿⣿⣿⣟⣟⣿⡿⠿⣿⣧⣭⣌⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⠿⠿⠿⠿⣾⣿⣿⣿⣻⣥⣶⣷⣾⣿⡿⡿⢿⠟⠻⢻⣻⣿⡇⣿⣽⢺⠀⡇⠀⠀⠀⠀⠀⠀⢸⢱⣿⣿⡿⣿⡿⢿⡿⣿⣾⣽⣾⣾⣿⣾⣿⣷⣿⣿⣿⣿⣿⣿⣯⣿⢧⢉⣿⠟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⠠⠄⠐⡠⣓⢁⡀⠀⠩⢟⠿⣿⣟⣻⣬⣵⣽⣦⣿⣳⣿⣿⣿⣇⣿⣼⣛⢨⠁⠀⢰⠀⠀⠀⠀⠸⢸⣿⠟⣼⣿⣿⣷⣾⣶⣮⣬⣧⣝⣎⢳⣿⣿⣟⣼⣿⣿⣿⣿⣿⣿⣶⣶⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢰⣶⣇⣀⡀⢀⠉⠁⠈⠀⠀⠀⢉⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣯⡟⣾⡇⢈⠀⠀⢸⠀⠀⠀⠀⢸⢸⣿⢾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣯⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣛⣿⢿⡿⣷⣤⣄⣀⢀⠀⠈⠀⠀⠀⠀⣫⠿⢿⣿⣿⣿⡟⣼⡇⣿⠇⢸⠀⠀⠈⠀⠀⠀⠄⢨⢼⣿⣾⡿⡇⣿⣿⣿⣿⡿⡟⣿⣿⠉⡛⢿⣿⣿⡿⠛⣿⣁⣬⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢘⠉⠀⠉⠙⠳⣾⠿⣻⣶⣄⣀⠠⢶⠴⠊⠀⠀⢎⣿⢿⣿⡟⣸⣧⠟⣥⣾⣿⣅⡀⠀⠀⠀⠀⠨⠚⠋⠻⠽⣇⣯⣟⣿⣿⣿⣿⣟⣁⣧⣠⣼⣿⣯⣶⡶⠟⠛⠛⠻⠿⢿⣿⣿⣿⠿⠿⠿⢿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣾⣶⡤⠒⠉⠀⡀⢠⢀⢻⡿⢋⣁⢠⠰⣾⡼⢚⣁⢎⣽⣷⣿⣿⣏⠿⣿⢿⣿⣿⣶⡀⠀⠀⠀⠒⠀⠀⠀⣀⠈⣙⣿⠿⢿⣿⣿⣿⣿⡿⣿⣥⠀⠈⠓⠾⣄⢄⠀⢀⣴⣿⣿⡟⣒⡠⠦⢆⠐⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣟⣧⣿⣾⣶⣶⣶⣇⡛⣁⣤⣫⣝⣾⣟⣭⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⡶⣸⣿⡿⠟⢡⢀⡲⠶⢶⠶⠂⠀⠈⠉⠁⠉⠀⠀⠀⠒⠉⠛⠛⠿⠿⠀⠀⠀⠀⠀⠉⠓⢿⠿⡛⠫⠍⣠⣶⡿⡿⣷⣄⡀⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣿⣿⣿⣿⣛⣻⢿⣿⣿⣿⣿⣿⣽⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣅⠢⢼⣥⣰⣧⣮⣶⣾⡤⢤⡀⢠⡀⢄⣀⣀⡀⢀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⣀⠤⠤⣀⣴⡟⣿⣷⣶⣿⡿⣦⣀⢈⡻⣛⣛⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣻⣿⣿⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣷⣾⣷⣿⣶⣾⣤⣽⣧⣖⣦⣤⣔⣀⠠⠿⢾⠿⠛⠑⠚⠻⢿⣿⡟⣈⣿⢿⡿⣹⣿⣏⡵⣟⡿⠿⢿⡿⢿⡿⢿⡿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⠈⠈⠻⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣷⣾⣽⣢⣿⣿⣿⣝⣻⠿⣿⣿⣙⢋⡛⣟⣛⣛⣛⣛⣛⣛⣛⣻⣟⣿⣻⣽⡭⣿⣿⣿⣿⣿⣾⣶⣼⣲⣴⣮⣿⣳⣿⣯⡟⣥⣿⢾⣷⣬⣷⣜⣯⣋⢝⡣⠞⣖⣲⠶⣼⣯⡝⣏⣛⣺⣝⣳⣳⣛⣿⣻⣽⣿⣿⣿⣿⣿⠿⡿⡿⣿⡇"<<endl;
                cout<<"⢀⠰⣦⠁⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣵⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣅⣾⣿⣯⠉⠛⢋⠙⣛⣻⣯⣽⣿⣿⠶⣿⣿⠿⠿⠿⢻⣭⣫⣉⣭⣿⣽⣷⣶⣶⣶⣖⣛⣛⣛⣿⣷⣿⡅"<<endl;
                cout<<"⢸⢳⢃⡼⢏⡗⢉⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⢿⣿⡿⣿⣯⣯⣿⣽⡿⢿⠿⠿⠾⣿⢿⡛⠢⢍⠭⠭⠉⢉⡉⣉⠈⣉⡙⠁⠉⠹⠟⡩⠏⠥⠽⠛⠿⠿⠟⢛⠛⢛⠯⢟⣛⠟⠻⠿⠿⠝⡇"<<endl;
                cout<<"⢸⣧⣶⣽⣻⣳⡿⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣾⣿⣻⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣀⠀⠂⠂⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⢀⠀⡀⠀⠀⠐⠀⠀⠀⡐⠈⠉⠋⠁⠀⠈⠐⠓⠸⠷⠶⠶⠿⠛⠋⠋⢙⡆⠀⠀⡐⠒⠹⠇⠀⠀⠀"<<endl;
                cout<<"⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣿⣿⣿⣿⣿⣿⣿⣿⠿⣿⣿⢿⡿⣿⠻⣿⠿⣿⣿⣻⢿⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⡀⠀⠀⠀⠀⠠⣄⣤⠦⡸⣤⢂⣙⡤⡤⢤⠄⡄⠠⠐⠘⠙⠶⠲⠞⠶⠖⠦⠶⠀⠄⠀⠀⠀⠀⠀⠈⠈⠁⠀⠀⠀⠀⠐⢈⠀⠐⡆"<<endl;
                cout<<"⢸⣿⣾⣿⣿⣳⣟⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⡩⠌⠉⠤⣉⡿⠁⠀⠁⠀⠛⠙⠿⣿⣿⣿⣿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀⠀⣄⣤⣤⠤⡄⢶⡶⣦⠤⣀⣠⣥⢄⣤⣴⣤⡀⣀⣤⣴⣶⣶⣦⣆⣄⣤⣴⣶⡶⣞⣡⣤⣶⣿⣿⣮⣿⣷⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣿⢿⣙⣾⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣴⣿⠟⢲⣦⠄⠀⠀⠀⠈⠐⠟⣿⣿⣿⣦⣝⠻⢿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡽⣿⣿⣟⣾⣿⣿⡼⠟⣙⣀⠁⢺⣷⣿⣿⣾⣶⣾⣼⣿⣵⣾⣿⢾⣿⣉⣯⣿⣿⣿⣿⣿⡝⣿⡿⢽⣍⡿⢿⣿⣿⣯⣿⣿⣷⣿⣿⡇"<<endl;
                cout<<"⢸⣟⣾⣿⣿⡿⣻⣟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣾⣏⡀⠏⣷⢷⡂⢄⣄⡀⠙⢿⣿⣿⣿⣦⣉⣚⡿⢮⣿⣻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡞⣤⡼⡏⠀⠀⠋⠠⣈⡼⡿⠻⢿⣿⣿⡛⢉⡛⣿⣿⠛⣟⣻⣩⣿⣿⣿⣿⣿⣿⣽⡶⣟⢧⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣿⣿⣟⡟⣼⣿⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣽⣶⡾⢷⣶⣿⣟⡿⢾⣿⣿⣿⣿⣿⣄⣀⠠⠎⠿⠏⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣭⣅⣹⣟⣀⣻⣿⣷⣩⣟⠃⣖⠂⢳⣯⣶⣷⠏⣿⢿⡾⢿⣿⣻⢾⣿⣿⣿⣿⣽⣿⣿⣾⣾⣟⣿⡿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣿⣞⣾⣴⣟⡏⡾⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣥⡞⣭⣷⣯⣝⣛⣿⣿⣿⣿⡾⡖⢲⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣧⡜⢼⣿⣿⣏⣻⡿⣿⣤⢈⠹⢄⠻⣿⣿⣿⣯⣬⣽⣳⣞⡷⣿⢯⣿⣻⢯⡿⢿⣟⠿⣿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⡇"<<endl;
                cout<<"⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⣳⣍⣿⣿⣷⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣼⣿⣞⣻⣟⡿⢷⡽⣥⢻⣟⣦⣣⣞⣯⡽⣿⢟⡿⣯⣷⣻⣽⣯⣿⣾⢿⣷⣽⣮⣥⣼⣽⣬⣿⣿⣮⣯⣿⣬⣿⣿⣿⡗"<<endl;
                cout<<"Ending 8/12 A Forgotten Loser"<<endl;
                cout<<"[xxxx-xxx8-xxxx]"<<endl;
                Credits();
    }
}